version: "v2.1.1"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8020:80
    volumes:
      - ./src:/var/www/html/
      # - ./img:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 3310:3306
